name: build

on:
  push:
    branches: [ci-cd]
  pull_request:
    branches: [ci-cd]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: build and test
        run: make

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx create --name mybuilder --bootstrap --use
          docker buildx build --platform linux/amd64,linux/arm64 -t docker.pkg.github.com/americanbinary/echoip/echoip/echoip:v1 --push .




            
            
    