name: build

on:
  push:
    branches: [ci-cd]
  pull_request:
    branches: [ci-cd]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
    
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: build and test
        run: make

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            docker.pkg.github.com/americanbinary/echoip/echoip/echoip:v1
            docker.pkg.github.com/americanbinary/echoip/echoip/echoip:${{ github.sha }}




            
            
    