name: build

on:
  pull_request:
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'master' && github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: build and test
        run: make

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          secrets: |
            "github_token=${{ secrets.GODMODEACTUAL }}"
          tags: |
            ghcr.io/americanbinary/echoip:latest




            
            
    