name: build

on:
  pull_request:
    branches: &branches
      - master
    types: [ opened, synchronize, reopened ]
  push:
    branches: *branches

env:
  APP: echoip
  APP_PKG: ./
  APP_DIR: ./
  AWS_ROLE_SUFFIX: repo-ecr-push
  AWS_ECS_SERVICE_NAME: repo-auth

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: build and test
        run: make

  version:
    runs-on: ubuntu-latest
    outputs:
      tag_version: "${{ steps.version_check.outputs.check_txt_contents }}"
      version: "${{ steps.version_check.outputs.version_value }}"
      previous_version: "${{ steps.version_check.outputs.previous_version_value }}"
    steps:
      - uses: actions/checkout@v7
      - run: git fetch --tags && git tag | head -n 1
      - id: version_check
        run: |
          ./.github/version_check.sh
          check_txt_contents=$(cat check.txt)
          echo "Version is $check_txt_contents"
          echo "check_txt_contents=${check_txt_contents}" >> "${GITHUB_OUTPUT}"
          version_value="$(cat version/version.go | grep 'const Version' | awk '{print $NF}' | tr -d '"')"
          echo "version_value=${version_value}" >> "${GITHUB_OUTPUT}"
          previous_version_value=$(git describe --tags $(git rev-list --tags --max-count=1) | tr -d 'v')
          echo "previous_version_value=${previous_version_value}" >> "${GITHUB_OUTPUT}"
      - name: debug
        env:
          TAG_VERSION: "${{ steps.version_check.outputs.check_txt_contents }}"
          VERSION: "${{ steps.version_check.outputs.version_value }}"
          PREVIOUS_VERSION: "${{ steps.version_check.outputs.previous_version_value }}"
        run: echo "version is ${VERSION} (previous = ${PREVIOUS_VERSION}) and TAG_VERSION is ${TAG_VERSION}"
      - name: same version error message
        if: steps.version_check.outputs.check_txt_contents == '1'
        run: |
          echo "::warning::version is same when compared to previous version please increment the release version for further release process"

  release:
    runs-on: ubuntu-latest
    needs: [ build, version ]
    if: needs.version.outputs.tag_version != '1' && github.event_name == 'push' && github.ref_name == 'master'
    env:
      TAG_VERSION: "${{ needs.version.outputs.tag_version }}"
      VERSION: "${{ needs.version.outputs.version }}"
      PREVIOUS_VERSION: "${{ needs.version.outputs.previous_version }}"
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          secrets: |
            "github_token=${{ secrets.GODMODEACTUAL }}"
          tags: |
            ghcr.io/americanbinary/echoip:latest
            ghcr.io/americanbinary/ambitclientbackendservice:v${VERSION}

  release-image-ambit-registry-dev:
    runs-on: ubuntu-latest
    needs: [ release, version ]
    if: needs.version.outputs.tag_version != '1'
    steps:
      - name: determine target environment
        env:
          github_event_name: "${{ github.event_name }}"
          github_ref_name: "${{ github.ref_name }}"
        run: |
          set -eux -o pipefail
          echo "target_environment=dev" >> "${GITHUB_ENV}"
          echo "target_repo=repo.dev.edge.ambit.inc" >> "${GITHUB_ENV}"
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: 'us-east-1'
          role-to-assume: 'arn:aws:iam::372108847118:role/${{ env.target_environment }}-image-reg-registry-push'
      - run: |
          set -eux -o pipefail
          token=$(
            curl -fSs -X POST "https://login.microsoftonline.com/3390a7ac-e80c-4cf8-a217-02099a3a22b7/oauth2/v2.0/token" \
              -H 'Content-Type: application/x-www-form-urlencoded' \
              --data-urlencode "client_id=8dd3d59c-6996-4134-beee-2f63dd62c43e" \
              --data-urlencode "client_secret=$(aws ssm get-parameter --with-decryption --name /${target_environment}/image-reg-auth-gha/repo-app-client-secret --output text --query Parameter.Value)" \
              --data-urlencode 'grant_type=client_credentials' \
              --data-urlencode "scope=api://${target_environment}-repo-int-app/.default" \
              | jq -r .access_token
          )
          echo "${token}" | docker login ${target_repo} -u Ambit --password-stdin
      - name: release image to registry
        env:
          VERSION: ${{ needs.version.outputs.VERSION }}
        run:
          set -eux -o pipefail
          docker buildx imagetools create \
          --tag ${target_repo}/${APP}:latest \
          --tag ${target_repo}/${APP}:v${VERSION}
          ;

  release-image-ambit-registry-prod:
    runs-on: ubuntu-latest
    needs: [ release, version ]
    if: needs.version.outputs.tag_version != '1'
    steps:
      - name: determine target environment
        env:
          github_event_name: "${{ github.event_name }}"
          github_ref_name: "${{ github.ref_name }}"
        run: |
          set -eux -o pipefail
          echo "target_environment=prod" >> "${GITHUB_ENV}"
          echo "target_repo=repo.edge.ambit.inc" >> "${GITHUB_ENV}"
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: 'us-east-1'
          role-to-assume: 'arn:aws:iam::372108847118:role/${{ env.target_environment }}-image-reg-registry-push'
      - run: |
          set -eux -o pipefail
          token=$(
            curl -fSs -X POST "https://login.microsoftonline.com/3390a7ac-e80c-4cf8-a217-02099a3a22b7/oauth2/v2.0/token" \
              -H 'Content-Type: application/x-www-form-urlencoded' \
              --data-urlencode "client_id=8dd3d59c-6996-4134-beee-2f63dd62c43e" \
              --data-urlencode "client_secret=$(aws ssm get-parameter --with-decryption --name /${target_environment}/image-reg-auth-gha/repo-app-client-secret --output text --query Parameter.Value)" \
              --data-urlencode 'grant_type=client_credentials' \
              --data-urlencode "scope=api://${target_environment}-repo-int-app/.default" \
              | jq -r .access_token
          )
          echo "${token}" | docker login ${target_repo} -u Ambit --password-stdin
      - name: release image to registry
        env:
          VERSION: ${{ needs.version.outputs.VERSION }}
        run:
          set -eux -o pipefail
          docker buildx imagetools create \
          --tag ${target_repo}/${APP}:latest \
          --tag ${target_repo}/${APP}:v${VERSION}
          ;